### ISSUE TITLE
Are you going to accept PRs here or only on gitlab?

### ISSUE THREAD

**Issue by paluh** [Thimoteus/purescript-parsecative#1]
Nice project!

Are you going to accept PRs and respond to issues here or do you prefer to manage it on gitlab?

**Comment by paluh** [comment]
P.S. it seems that `test/Main.purs` has some minor import related bugs. I can provide a PR if you want.

**Comment by Thimoteus** [comment]
I have gitlab set up to automatically push changes from there to here, so I'd prefer to manage it on gitlab. Thanks! If that's fine with you I'll accept a PR for the test there, otherwise I can take care of it.

**Comment by paluh** [comment]
I think I have somewhere gitlab account... I'm going to fork your lib there.
