### ISSUE TITLE
Does Annihilation hold?

### ISSUE THREAD

**Issue by paluh** [Thimoteus/purescript-parsecative#2]
It seems to me that this should accumulate both errors:
```
empty <*> fail "another error"
```

Here is my quick experiment: https://github.com/paluh/purescript-parsecative/blob/annihilation/test/Main.purs#L61

Does this break `Annihilation` law then?

**Comment by paluh** [comment]
Sorry, I should rather write `empty <*> empty`.

**Comment by paluh** [comment]
F*** it should be `empty <$> empty` so it holds ;-) Sorry for this spam.

**Comment by Thimoteus** [comment]
When I was writing the instance I thought it might break something, since the alternative would be to define something like `empty = Parsecative \_ -> ContT (_ $ invalid mempty)`, which "looks" more law-abiding (since it's defined in terms of `mempty`) than providing a custom error message. At the time I thought it was worth it to provide a builtin error message vs no message at all, but I didn't feel strongly one way or the other.

**Comment by paluh** [comment]
Ok, so maybe a it is worth a comment because it had confused me a bit ;-)

**Comment by paluh** [comment]
Recently I'm investigating different `Applicative` and `Alternative` implementations of validators/parsers too :-).
I have this `Dual` type which in theory would work with your `Parsecative`. But to make it really useful we should be able to implement this `diverge` function: https://github.com/paluh/purescript-polyform/blob/redesign/src/Polyform/Dual.purs#L95 which depends on `Profunctor` instance.

I don't think it is possible to provide `Profunctor` or `Contravariant`instance when you have `Ref` on the negative postion. Am I right?

**Comment by Thimoteus** [comment]
Actually, I think right identity fails:

```
parse (fail ["THIS ERROR MESSAGE IS NOT SHOWN"] <|> empty :: Parsecative ParserError String Unit) "" logResult
```

But it's also a problem with e.g. `purescript-parsing`:

```
logShow $ runParser "" (fail "THIS ISN'T SHOWN EITHER" <|> empty :: Parser String Unit)
```

**Comment by Thimoteus** [comment]
I'll have to think about profunctors. You mean with respect to the stream type (aka state) or with respect to the error type? One of them is positive, the other negative.

**Comment by paluh** [comment]
I think about stream type.

**Comment by Thimoteus** [comment]
Ahh, I see now. There's `withState :: ∀ e s a. (s -> s) -> Parsecative e s a -> Parsecative e s a` because I couldn't figure out how to implement it where the state type changes given `s -> s'`. It could be that it's impossible, in which case that would also apply to a `Profunctor` instance.

**Comment by Thimoteus** [comment]
Wait, I think I just figured it out ... commit incoming

**Comment by paluh** [comment]
Sorry for taking your time. I'm talking bulshit. I don't really need `Profunctor` at all :-)

So I can use your lib to build invertiable parser using your lib + Dual even now :-)

**Comment by Thimoteus** [comment]
Well, the new type is `withState :: ∀ e s s' a. (s' -> s) -> Parsecative e s a -> Parsecative e s' a` which I think is exactly what `Profunctor` needs.

**Comment by paluh** [comment]
Ooo that is interesting and useful anyway I think :-)

**Comment by paluh** [comment]
P.S.
@Thimoteus I think that you have so much interesting libs and tools that you should promote them more! I'm trying to force authors like you to post some announces on discourse so our ecosystem and community can be seen as vibrant as it is in reality :-)
